name = "BeamTracking"
uuid = "8ef5c10a-4ca3-437f-8af5-b84d8af36df0"
authors = ["mattsignorelli <mgs255@cornell.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
AcceleratorLattice = "118f53b2-f4ec-480a-a460-1a04f660b17d"
GTPSA = "b27dd330-f138-47c5-815b-40db9dd9b6e8"

[compat]
julia = "1.9"
GTPSA = "0.6.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
